version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
#      DATABASE_URL: postgres://postgres:root@postgres:5432/bank
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank
    ports:
      - "35000:5432"
  postgres_admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: pwdPGadmin
    ports:
      - "5050:80"
